const Faq = ()=> {
    return (
        <div id="faq">
            <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas laboriosam odio harum, asperiores nemo eum ut labore neque nihil quidem, qui saepe eos molestias, cum placeat unde doloremque odit. Nulla, tempora illum. Ipsa at sequi, veniam quibusdam explicabo facere. Laudantium ducimus quas, reiciendis libero debitis quae. Dolorum alias veniam earum? Ea, aspernatur veritatis harum libero magni nostrum, voluptas rem et nesciunt asperiores esse ipsam saepe perspiciatis? Debitis eius repellat dolorem explicabo assumenda incidunt ipsa ipsum facilis tenetur nostrum dolorum veritatis, repellendus ullam mollitia nisi ratione animi eligendi dolore aliquid. Facere commodi modi quam accusantium dolore impedit illo consequuntur reiciendis ea!</p>
            <h1>Lorem ipsum, dolor sit amet consectetur adipisicing.</h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur praesentium perspiciatis laboriosam ullam dicta est amet nobis esse optio sequi necessitatibus error et unde impedit, repellat at molestias animi, tempore iure laborum ratione sunt asperiores? Obcaecati excepturi impedit distinctio suscipit consequatur adipisci, veniam hic aspernatur quos nobis dolor! Excepturi dicta officia aliquam ducimus, blanditiis veritatis ipsam impedit at quam, id voluptate est corrupti praesentium, incidunt eligendi quas modi aliquid quos iusto tenetur officiis voluptatum harum similique! Obcaecati ipsa fugit modi adipisci. Optio, odio dicta ad ipsam nisi possimus fugit dolor velit nemo dolorem, aliquam aspernatur non quia vel excepturi necessitatibus?</p>
            <h1>Lorem ipsum dolor sit amet consectetur adipisicing.</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse, dignissimos similique fugit consectetur aut maxime ut! Cum nostrum dolore odio, magni deserunt, minima dignissimos officia nemo accusantium, perspiciatis deleniti est. Harum vero a modi tempora consectetur! Aut praesentium ab hic quis, laboriosam ullam quibusdam laborum debitis minus eius cumque perferendis incidunt ipsa, laudantium numquam minima accusantium id aliquid, eaque vitae reiciendis suscipit? Hic laudantium illum deleniti, nam minima provident voluptatibus fuga impedit officia architecto. Amet aspernatur a cumque! Debitis suscipit neque nesciunt asperiores explicabo, et veritatis laudantium enim iste, ut ipsa repudiandae sapiente ea, ad possimus dolorum ullam hic animi?</p>
            <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit.</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt aspernatur obcaecati eos, similique optio veniam quasi ad corrupti dicta, minus hic? Obcaecati ipsa, voluptates consectetur impedit id dolorem praesentium quas, voluptatum accusantium blanditiis quisquam suscipit dolorum laudantium minima facilis fuga odit? Veritatis excepturi non, quae sapiente ratione sunt est eveniet repudiandae, fugiat aspernatur animi inventore eaque. Veniam, eligendi ullam! Totam, iure cupiditate. Voluptate, recusandae non sed voluptatibus dignissimos iste impedit amet et culpa. Neque cupiditate eveniet excepturi, fuga suscipit aperiam eum totam illum ipsam ex vero fugit saepe quos laborum voluptates itaque dolor minus consectetur! Laborum dolores repellendus vero assumenda.</p>
        </div>
    )
}
export { Faq };