const express=require("express");
const app=express();
let books={
    BOOK1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque lacus nulla, molestie eu neque eget, condimentum faucibus libero. Aenean egestas, lorem nec condimentum tempus, lectus justo fermentum mi, sed elementum velit quam ac mi. Morbi faucibus egestas nisi eget porttitor. Suspendisse nec arcu pharetra, varius dui eu, scelerisque orci. Pellentesque ut magna ac magna pulvinar gravida. Vivamus mollis felis a ex cursus porta. Integer ac ligula a quam hendrerit imperdiet.Integer rutrum id sem sed ultricies. Vestibulum justo ligula, vestibulum et facilisis imperdiet, porttitor ut lectus. In a fringilla leo. Nullam lacinia venenatis scelerisque. Mauris vel nunc sit amet quam imperdiet tristique. Donec blandit nibh eu justo condimentum ornare. Duis eu laoreet ante, quis ullamcorper nulla. Nulla ut ligula vehicula, varius ipsum eget, faucibus nunc. Proin id tristique metus. Vivamus elementum, purus at placerat rutrum, dolor lorem laoreet sem, at iaculis lectus mi eu risus. Vivamus id nulla et nunc placerat egestas eget et nulla. Nullam vel luctus tellus, nec consectetur neque. Donec auctor congue est eu scelerisque. Suspendisse accumsan molestie dictum.",

    BOOK2:"Donec at urna lectus. In gravida aliquet leo. Aenean sed auctor ex, pellentesque suscipit mauris. Curabitur dui mi, rhoncus eget nulla sed, placerat suscipit dolor. Nulla mattis eros id dui cursus, vel faucibus ante ornare. Donec bibendum at quam id mollis. Fusce viverra viverra dignissim. Aliquam tristique ac orci a cursus. Mauris pretium dignissim lacus quis tempor.",

    BOOK3:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque lacus nulla, molestie eu neque eget, condimentum faucibus libero. Aenean egestas, lorem nec condimentum tempus, lectus justo fermentum mi, sed elementum velit quam ac mi. Morbi faucibus egestas nisi eget porttitor. Suspendisse nec arcu pharetra, varius dui eu, scelerisque orci. Pellentesque ut magna ac magna pulvinar gravida. Vivamus mollis felis a ex cursus porta. Integer ac ligula a quam hendrerit imperdiet.Integer rutrum id sem sed ultricies. Vestibulum justo ligula, vestibulum et facilisis imperdiet, porttitor ut lectus. In a fringilla leo. Nullam lacinia venenatis scelerisque. Mauris vel nunc sit amet quam imperdiet tristique. Donec blandit nibh eu justo condimentum ornare. Duis eu laoreet ante, quis ullamcorper nulla. Nulla ut ligula vehicula, varius ipsum eget, faucibus nunc. Proin id tristique metus. Vivamus elementum, purus at placerat rutrum, dolor lorem laoreet sem, at iaculis lectus mi eu risus. Vivamus id nulla et nunc placerat egestas eget et nulla. Nullam vel luctus tellus, nec consectetur neque. Donec auctor congue est eu scelerisque. Suspendisse accumsan molestie dictum.",

    BOOK4:"Donec at urna lectus. In gravida aliquet leo. Aenean sed auctor ex, pellentesque suscipit mauris. Curabitur dui mi, rhoncus eget nulla sed, placerat suscipit dolor. Nulla mattis eros id dui cursus, vel faucibus ante ornare. Donec bibendum at quam id mollis. Fusce viverra viverra dignissim. Aliquam tristique ac orci a cursus. Mauris pretium dignissim lacus quis tempor."
}
app.listen(5000)
app.get("/books",(req,res)=>{res.send(JSON.stringify(books))})